name: grocery_vision
description: "A new Flutter project."


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: ^3.10.7







dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.2
  haptic_feedback: ^0.5.1



  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  google_sign_in: ^7.2.0
  camera: ^0.12.0+1
  firebase_ai: ^3.11.0
  cloud_firestore: ^6.3.0
  flutter_tts: ^4.2.5
  path_provider: ^2.1.5
  http: ^1.6.0
  google_fonts: ^8.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0





flutter:




  uses-material-design: true
